In [2]:
import numpy as np

In [3]:
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
type(my_list)

list

In [4]:
ar = np.array(my_list)
type(ar)

numpy.ndarray

In [5]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_list*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
ans = []
for i in my_list:
    ans.append(2*i)
    
ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [10]:
ar*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2*a)
print(2*a + b)

[2 4 6]
[12 24 36]


In [12]:
a == 2

array([False,  True, False])

In [13]:
b > 10

array([False,  True,  True])

In [15]:
c = np.array([[0, 1, 3], [3, 4, 5]])
c

array([[0, 1, 3],
       [3, 4, 5]])

In [23]:
c[-1, -1]

5

In [24]:
c[0,:]

array([0, 1, 3])

In [25]:
c[:, 1]

array([1, 4])

In [26]:
c[:2, :2]

array([[0, 1],
       [3, 4]])

In [18]:
d = np.array([  [[1,2,3, 4], 
              [5,6,7,8],
              [9,10,11,12]],
              [[13, 14, 15, 16],
              [17, 18, 19, 20],
              [21, 22, 23, 24]]]
    
)

In [19]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [20]:
a = np.array([0, 10, 20, 30, 40])

In [21]:
a[-1]

40

In [22]:
a[2]

20

In [27]:
m = np.array([[0, 1, 2, 3, 4],
              [5, 6, 7, 8, 9],
              [10, 11, 12, 13, 14]])

In [28]:
m[1,2]

7

In [29]:
m[-1, -1]

14

In [31]:
m[1, 1:3]

array([6, 7])

In [32]:
m[1:,2]

array([ 7, 12])

In [34]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [ ]:
m[1,2]
m[-1, -1]
m[1, 1:3]
m[1:,2]
m[:2,3:]

In [43]:
a = np.array([0, 1, 2, 3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [39]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [40]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [44]:
a = np.array([[1,2 ,3, 4],
              [5,6,7,8],
              [9 , 10, 11, 12]])

In [45]:
a[:, [True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [47]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [49]:
x=np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [48]:
x = np.array([1, 2, 3.0])
print(x.dtype)

float64


In [52]:
m = np.array([ 0,  1,  2,  3,  4], dtype='U')
m[2]+m[4]

'24'

In [53]:
c = np.zeros((5, 2), dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [54]:
d = np.zeros(5, dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [56]:
d[0] = "abc"
d[1] = "abcd"
d

array(['abc', 'abcd', '', '', ''], dtype='<U4')

In [58]:
e = np.ones((2, 3, 4), dtype='i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [59]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [62]:
a = np.arange(12)

In [63]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
a = tf.constant(7.0, name='data1')
b = tf.constant(3.0, name='data1')
c = tf.constant(2.0, name='data1')

v = a*b/c

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(v))


Instructions for updating:
non-resource variables are not supported in the long term
10.5


In [2]:
# 커널 재시작
import tensorflow as tf

a = tf.constant(7.0, name='data1')
b = tf.constant(3.0, name='data2')
c = tf.constant(2.0, name='data3')

v = a * b / c

print(v)
print(v.numpy())

tf.Tensor(10.5, shape=(), dtype=float32)
10.5


In [14]:
import tensorflow as tf
data = [[2, 81], [4, 93], [6, 91], [8, 97]]
x_train = [x_row[0] for x_row in data]
y_train = [y_row[1] for y_row in data]

w = tf.Variable(tf.random.uniform([1], 0, 10, dtype=tf.float64, seed=0))
b = tf.Variable(tf.random.uniform([1], 0, 100, dtype=tf.float64, seed=0))

def hypothesis(w, b):
    return x_train*w + b

def cost(w, b):
    return tf.sqrt(tf.reduce_mean(tf.square(hypothesis(w, b) - y_train)))

opt = tf.keras.optimizers.SGD(learning_rate=0.1)
for i in range(2000):
    with tf.GradientTape() as tape:
        loss = cost(w, b)
        
    gradients = tape.gradient(loss, [w, b])
    opt.apply_gradients(zip(gradients, [w, b]))
    if i%100 == 0:
        print(i, f'{cost(w, b)}, {w.numpy()}, {b.numpy()}')

0 15.764082919229716, [8.04917214], [41.59726869]
100 13.947752281508823, [7.90121337], [45.57435405]
200 12.404125622912817, [7.25188305], [49.44927973]
300 10.882408886270415, [6.60717415], [53.29662672]
400 9.392671129873015, [5.96927096], [57.10336013]
500 7.951533155706767, [5.34185382], [60.84751731]
600 6.587401753172817, [4.73142824], [64.49027609]
700 5.349244387767643, [4.1498991], [67.9605933]
800 4.31535658312989, [3.61866405], [71.13077691]
900 3.577282243304263, [3.17037182], [73.80599322]
1000 3.1623789311676216, [2.8352444], [75.8058903]
1100 2.9811476498320033, [2.61452428], [77.12305361]
1200 2.9145267883184696, [2.48099566], [77.9198953]
1300 2.8919539947953377, [2.40334354], [78.38328994]
1400 2.884537815338748, [2.35884921], [78.6488131]
1500 2.8821268024067512, [2.33348242], [78.80019125]
1600 2.881345694537694, [2.31904448], [78.88635071]
1700 2.8810929208839573, [2.31083131], [78.93536336]
1800 2.8810111509625, [2.30615999], [78.9632398]
1900 2.880984702289327, 