In [1]:
import pandas as pd

In [2]:
s = pd.Series([23456,65342,34567,84564])

In [3]:
print(s)
print(type(s))

0    23456
1    65342
2    34567
3    84564
dtype: int64
<class 'pandas.core.series.Series'>


In [4]:
print(s.values)
print(type(s.values))

[23456 65342 34567 84564]
<class 'numpy.ndarray'>


In [39]:
s = pd.Series([23456,65342,34567,84564],
              index=["서울", "부산", "대전", "대구"])

print(s)

서울    23456
부산    65342
대전    34567
대구    84564
dtype: int64


In [7]:
myPDS = pd.Series(range(10, 14))
myPDS

0    10
1    11
2    12
3    13
dtype: int64

In [8]:
s.index

Index(['서울', '부산', '대전', '대구'], dtype='object')

In [9]:
s.values

array([23456, 65342, 34567, 84564])

In [10]:
print(type(s.index))
print(type(s.values))

<class 'pandas.core.indexes.base.Index'>
<class 'numpy.ndarray'>


In [11]:
print(s.name)
print(s.index.name)

None
None


In [12]:
s.name = "인구 분석"
s.index.name = "도시"
print(s)

도시
서울    23456
부산    65342
대전    34567
대구    84564
Name: 인구 분석, dtype: int64


In [13]:
s/10000

도시
서울    2.3456
부산    6.5342
대전    3.4567
대구    8.4564
Name: 인구 분석, dtype: float64

In [14]:
s

도시
서울    23456
부산    65342
대전    34567
대구    84564
Name: 인구 분석, dtype: int64

In [15]:
print(s.iloc[1], s.loc["부산"])

65342 65342


In [16]:
print(s[1], s["부산"])

65342 65342


/var/folders/wm/j89vyk052m5bvrvn1dhfyflr0000gn/T/ipykernel_58167/144680482.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1], s["부산"])


In [17]:
print(s.iloc[3], s["대구"])

84564 84564


In [18]:
s.iloc[[0, 3, 1]]

도시
서울    23456
대구    84564
부산    65342
Name: 인구 분석, dtype: int64

In [21]:
s[["서울", "대구", "부산"]]

도시
서울    23456
대구    84564
부산    65342
Name: 인구 분석, dtype: int64

In [22]:
240e4

2400000.0

In [23]:
24e3 < s

도시
서울    False
부산     True
대전     True
대구     True
Name: 인구 분석, dtype: bool

In [24]:
type(24e3 < s)

pandas.core.series.Series

In [26]:
s[(24e3 < s) & (45e3 < s)]

도시
부산    65342
대구    84564
Name: 인구 분석, dtype: int64

In [27]:
s[1:3]

도시
부산    65342
대전    34567
Name: 인구 분석, dtype: int64

In [28]:
s["부산":"대구"]

도시
부산    65342
대전    34567
대구    84564
Name: 인구 분석, dtype: int64

In [30]:
for k, v in s.items():
    print("%s = %d" % (k, v))

서울 = 23456
부산 = 65342
대전 = 34567
대구 = 84564


In [31]:
s2 = pd.Series({"서울": 12345, "부산":34565, "인천": 43256, "대전": 56788})
s2

서울    12345
부산    34565
인천    43256
대전    56788
dtype: int64

In [33]:
s2 = pd.Series({"서울": 12345, "부산":34565, "인천": 43256, "대전": 56788},
               index=["부산", "서울", "인천", "대구"])
s2


부산    34565.0
서울    12345.0
인천    43256.0
대구        NaN
dtype: float64

In [34]:
s

도시
서울    23456
부산    65342
대전    34567
대구    84564
Name: 인구 분석, dtype: int64

In [40]:
ds = s - s2
ds

대구        NaN
대전        NaN
부산    30777.0
서울    11111.0
인천        NaN
dtype: float64

In [41]:
type(s.values)

numpy.ndarray

In [42]:
s.values

array([23456, 65342, 34567, 84564])

In [43]:
print(s2.values)

[34565. 12345. 43256.    nan]


In [44]:
s.values - s2.values

array([-11109.,  52997.,  -8689.,     nan])

In [46]:
myd = ds.notnull()

In [47]:
type(myd)

pandas.core.series.Series

In [48]:
ds[ds.notnull()]

부산    30777.0
서울    11111.0
dtype: float64

In [49]:
s

서울    23456
부산    65342
대전    34567
대구    84564
dtype: int64

In [50]:
s2

부산    34565.0
서울    12345.0
인천    43256.0
대구        NaN
dtype: float64

In [51]:
rs = (s - s2) / s *100
rs = rs[rs.notnull()]
rs

부산    47.101405
서울    47.369543
dtype: float64

In [52]:
rs["부산"]= 1.63

In [53]:
rs

부산     1.630000
서울    47.369543
dtype: float64

In [54]:
del rs['서울']
rs

부산    1.63
dtype: float64

In [55]:
data = [['John', 28, 'Male'],
        ['Kate', 23, 'Female'],
        ['David', 31, 'Male'],
        ['Emily', 27, 'Female']]

columns = ["Name", "Age", "Gender"]
df = pd.DataFrame(data, columns=columns)

print(df)

    Name  Age  Gender
0   John   28    Male
1   Kate   23  Female
2  David   31    Male
3  Emily   27  Female


In [56]:
print(df.values)
print(df.columns)
print(df.index)

[['John' 28 'Male']
 ['Kate' 23 'Female']
 ['David' 31 'Male']
 ['Emily' 27 'Female']]
Index(['Name', 'Age', 'Gender'], dtype='object')
RangeIndex(start=0, stop=4, step=1)


In [57]:
print(type(df.values))
print(type(df.columns))
print(type(df.index))

<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.range.RangeIndex'>


In [58]:
df[0]

KeyError: 0

In [59]:
print(df)

    Name  Age  Gender
0   John   28    Male
1   Kate   23  Female
2  David   31    Male
3  Emily   27  Female


In [60]:
print(df["Name"][0])

John


In [61]:
df1 = pd.DataFrame(data)

In [62]:
df1[0]

0     John
1     Kate
2    David
3    Emily
Name: 0, dtype: object

In [63]:
df1[0][0]

'John'

In [64]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]

df = pd.DataFrame(data, index=index, columns=columns)
print(df)
df

     지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141


지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [65]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [66]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [67]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [69]:
df.index.name = "도시"
df.columns.name = '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [70]:
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [71]:
df["2010-2015 증가율"] = ((df["2010"] - df["2005"])/df["2005"] * 100).round(2)

In [72]:
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [73]:
df['지역']

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [74]:
type(df['지역'])

pandas.core.series.Series

In [76]:
type(df[["2010", "2015"]])

pandas.core.frame.DataFrame

In [77]:
df[["2010", "2015"]]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [78]:
type(df["2010"])

pandas.core.series.Series

In [80]:
type(df[["2010"]])

pandas.core.frame.DataFrame

In [81]:
df["2010"]

도시
서울    9631482
부산    3393191
인천    2632035
대구    2431774
Name: 2010, dtype: int64

In [84]:
import numpy as np

In [85]:
df2 = pd.DataFrame(np.arange(12).reshape(3, 4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [86]:
df[:1]

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [87]:
df[1:2]

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437           -3.4

In [88]:
df[1:3]

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [89]:
df["서울":"부산"]

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [90]:
df["2015"]["서울"]

9904312

피마 인디언 실습

In [2]:
import numpy as np

In [4]:
dataset = np.loadtxt('data/pima-indians-diabetes.csv', delimiter=',')

In [5]:
x_train = dataset[:700, 0:8]
y_train = dataset[:700, 8]
x_test = dataset[700:, 0:8]
y_test = dataset[700:, 8]

In [7]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
import numpy
import tensorflow as tf
seed = 0
numpy.random.seed (seed)
tf.random.set_seed (seed)

In [13]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [14]:
model.compile(loss='binary_crossentropy' , optimizer='adam', metrics=['accuracy'])
model. fit(x_train, y_train, epochs=30, batch_size=10)

Epoch 1/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 302us/step - accuracy: 0.3681 - loss: 11.4355 
Epoch 2/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 235us/step - accuracy: 0.5740 - loss: 1.4249
Epoch 3/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 228us/step - accuracy: 0.5768 - loss: 1.0955
Epoch 4/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 224us/step - accuracy: 0.6135 - loss: 0.9479
Epoch 5/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 230us/step - accuracy: 0.6120 - loss: 0.8849
Epoch 6/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 233us/step - accuracy: 0.6156 - loss: 0.8320
Epoch 7/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 226us/step - accuracy: 0.6172 - loss: 0.7956
Epoch 8/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.6194 - loss: 0.7698
Epoch 9/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 236us/step - accuracy: 0.6266 - loss: 0.7475
Epoch 10/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 231us/step - accuracy: 0.6315 - loss: 0.7246
Epoch 11/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 229us/step - accuracy: 0.6415 - loss: 0.7055
Epoch 12/30
70/70 ━━━━━━━━━━━━━━━━━━━━ 0s 230us/st

In [15]:
scores = model.evaluate(x_test, y_test)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6209 - loss: 0.7395 
compile_metrics: 63.24%


In [17]:
import pandas as pd
df = pd.read_csv('data/pima-indians-diabetes.csv',
                names = ["pregnant", "plasma", "pressure", "thickness", "insulin", "BMI", "pedigree", "age", "class"])

In [18]:
print(df)

     pregnant  plasma  pressure  thickness  insulin   BMI  pedigree  age  \
0           6     148        72         35        0  33.6     0.627   50   
1           1      85        66         29        0  26.6     0.351   31   
2           8     183        64          0        0  23.3     0.672   32   
3           1      89        66         23       94  28.1     0.167   21   
4           0     137        40         35      168  43.1     2.288   33   
..        ...     ...       ...        ...      ...   ...       ...  ...   
763        10     101        76         48      180  32.9     0.171   63   
764         2     122        70         27        0  36.8     0.340   27   
765         5     121        72         23      112  26.2     0.245   30   
766         1     126        60          0        0  30.1     0.349   47   
767         1      93        70         31        0  30.4     0.315   23   

     class  
0        1  
1        0  
2        1  
3        0  
4        1  
..     ..

In [19]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pregnant   768 non-null    int64  
 1   plasma     768 non-null    int64  
 2   pressure   768 non-null    int64  
 3   thickness  768 non-null    int64  
 4   insulin    768 non-null    int64  
 5   BMI        768 non-null    float64
 6   pedigree   768 non-null    float64
 7   age        768 non-null    int64  
 8   class      768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None


In [20]:
print(df.describe())

         pregnant      plasma    pressure   thickness     insulin         BMI  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

         pedigree         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%   

In [21]:
print(df[['pregnant', 'class']])

     pregnant  class
0           6      1
1           1      0
2           8      1
3           1      0
4           0      1
..        ...    ...
763        10      0
764         2      0
765         5      0
766         1      1
767         1      0

[768 rows x 2 columns]


In [24]:
print( df[['pregnant', 'class']].groupby(['pregnant'], as_index=False).mean().sort_values (by='pregnant', ascending=True))

    pregnant     class
0          0  0.342342
1          1  0.214815
2          2  0.184466
3          3  0.360000
4          4  0.338235
5          5  0.368421
6          6  0.320000
7          7  0.555556
8          8  0.578947
9          9  0.642857
10        10  0.416667
11        11  0.636364
12        12  0.444444
13        13  0.500000
14        14  1.000000
15        15  1.000000
16        17  1.000000


In [ ]:
import matplotlib.pyplot 