In [2]:
import numpy as np

# 랜덤 데이터 생성
def generate_data(num_samples=1000):
    X = []
    y = []
    for _ in range(num_samples):
        sample = np.random.randint(1, 11, size=5)
        X.append(sample)
        y.append(sample[::-1])
    return np.array(X), np.array(y)

X, y = generate_data()

print("입력 데이터 예시:", X[:5])
print("입력 데이터 예시:", y[:5])

입력 데이터 예시: [[ 4  4 10 10  5]
 [ 7  7  4  9  8]
 [ 4  3  5 10  9]
 [ 8  2  7  8  2]
 [ 3  7  2  3  1]]
입력 데이터 예시: [[ 5 10 10  4  4]
 [ 8  9  4  7  7]
 [ 9 10  5  3  4]
 [ 2  8  7  2  8]
 [ 1  3  2  7  3]]


In [8]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# 모델 정의
model = Sequential([
    LSTM(100, input_shape=(5, 1)),
    Dense(5, activation='linear')
])

model.compile(optimizer='adam', loss='mse')

# 데이터 reshape
X = X.reshape(-1, 5, 1)
y = y.reshape(-1, 5)

# 모델 학습
model.fit(X, y, epochs=20, batch_size=32)


Epoch 1/20


/opt/anaconda3/lib/python3.11/site-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 30.3293   
Epoch 2/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.0629 
Epoch 3/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.2050
Epoch 4/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.1257 
Epoch 5/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 4.8716 
Epoch 6/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3.6845 
Epoch 7/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.8833 
Epoch 8/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.0572
Epoch 9/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1.4613 
Epoch 10/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.9936 
Epoch 11/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.6475 
Epoch 12/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4231 
Epoch 13/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.3451 
Epoch 14/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2732 
Epoch 15/20
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.2224 
Epoch 16/20
32

In [9]:
def reverse_input(input_str):
    # 입력 문자열을 리스트로 변환
    input_list = [int(x) for x in input_str]
    # numpy 배열로 변환 후 모델 입력 형태로 reshape
    input_array = np.array(input_list).reshape(1, 5, 1)
    # 모델 예측
    prediction = model.predict(input_array, verbose=0)
    # 예측 결과를 정수로 변환하여 리스트로 변환
    result = [int(round(x)) for x in prediction[0]]
    return ''.join(map(str, result))

# 입력 반복
while True:
    user_input = input("숫자 5개를 입력하세요 (Quit 입력 시 종료): ")
    if user_input.lower() == 'quit':
        break
    elif len(user_input) == 5 and user_input.isdigit():
        print(user_input, "거꾸로 출력:", reverse_input(user_input))
    else:
        print("잘못된 입력입니다. 숫자 5개를 입력하세요.")

12345 거꾸로 출력: 54321
98765 거꾸로 출력: 56799
45678 거꾸로 출력: 87654


In [15]:
# 100개의 예제 데이터 생성 (추론용)
X_test, y_test = generate_data(100)

# 데이터 reshape
X_test = X_test.reshape(-1, 5, 1)

# 예측 및 결과 출력
print("입력 데이터 -> 모델 예측 -> 실제 출력")
for i in range(100):
    input_data = X_test[i].reshape(1, 5, 1)
    prediction = model.predict(input_data, verbose=0)
    prediction = [int(round(x)) for x in prediction[0]]
    input_str = ''.join(map(str, X_test[i].reshape(5)))
    predicted_str = ''.join(map(str, prediction))
    actual_str = ''.join(map(str, y_test[i]))
    print(f"{input_str} -> {predicted_str} -> {actual_str}")

입력 데이터 -> 모델 예측 -> 실제 출력
73671 -> 17637 -> 17637
495109 -> 99594 -> 910594
791068 -> 861097 -> 861097
561103 -> 310165 -> 310165
241012 -> 21942 -> 211042
82513 -> 31528 -> 31528
89628 -> 82698 -> 82698
283410 -> 104382 -> 104382
6410510 -> 1051046 -> 1051046
57365 -> 56285 -> 56375
37171 -> 27173 -> 17173
92442 -> 24429 -> 24429
28574 -> 47591 -> 47582
49211 -> 21294 -> 11294
84941 -> 14948 -> 14948
1093210 -> 92499 -> 1023910
110356 -> 653102 -> 653101
42413 -> 31424 -> 31424
518210 -> 92715 -> 102815
483105 -> 510384 -> 510384
98793 -> 39789 -> 39789
1077101 -> 19779 -> 1107710
61714 -> 41716 -> 41716
487610 -> 106784 -> 106784
27591 -> 18572 -> 19572
42389 -> 98324 -> 98324
23798 -> 89732 -> 89732
13464 -> 46431 -> 46431
38672 -> 27682 -> 27683
84357 -> 75349 -> 75348
28394 -> 49382 -> 49382
291043 -> 341092 -> 341092
104592 -> 295410 -> 295410
42554 -> 45524 -> 45524
86544 -> 44569 -> 44568
981410 -> 94188 -> 104189
96799 -> 99769 -> 99769
91983 -> 38929 -> 38919
15359 -> 95351 ->

# 정답 

In [18]:
import numpy as np 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.layers import Bidirectional 
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense, Dropout, Activation
#학습데이터 생성
train_data = np.random.randint(0, 10, size=(10000, 5))
label_data = np.flip(train_data, axis=1)
print(train_data[:4])
print(label_data[:4])

from tensorflow.keras.preprocessing.text import Tokenizer 
from tensorflow.keras.preprocessing.sequence import pad_sequences
#pad_sequence 전처리
padded_train = pad_sequences(train_data, maxlen=5)
print(padded_train[0])
#모델링
model = Sequential()
model.add(Embedding(10,100, input_length=5))
model.add(Bidirectional(LSTM(64, return_sequences=True))) 
model.add(Dense(10,activation='softmax'))
# 모델의 요약을 보기 위해 한 번 모델을 호출하여 초기화합니다
model.build(input_shape=(None, 5))
model.summary()

[[8 2 1 0 9]
 [5 1 0 4 1]
 [4 0 2 4 2]
 [4 1 0 5 7]]
[[9 0 1 2 8]
 [1 4 0 1 5]
 [2 4 2 0 4]
 [7 5 0 1 4]]
[8 2 1 0 9]


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 5, 100)         │         1,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_3 (Bidirectional) │ (None, 5, 128)         │        84,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 5, 10)          │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 86,770 (338.95 KB)

 Trainable params: 86,770 (338.95 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
#모델 컴파일
model. compile(loss='sparse_categorical_crossentropy', optimizer='adam' ,metrics=['accuracy'])
#모델 실행
history = model.fit(padded_train, label_data, epochs=10, batch_size=32, validation_split=0.2)
# loss? accuracy
loss, acc = model. evaluate(padded_train, label_data)
print(f"loss : {loss:.4f}, acc = {acc:.4f}")
# 입력받아 예측하는 프로그램 작성


Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.3485 - loss: 1.8580 - val_accuracy: 0.5405 - val_loss: 1.0724
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5535 - loss: 1.0213 - val_accuracy: 0.5827 - val_loss: 0.9309
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5984 - loss: 0.8831 - val_accuracy: 0.6285 - val_loss: 0.8098
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6631 - loss: 0.7635 - val_accuracy: 0.7183 - val_loss: 0.6815
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7507 - loss: 0.6340 - val_accuracy: 0.7935 - val_loss: 0.5568
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8357 - loss: 0.4875 - val_accuracy: 0.8678 - val_loss: 0.4032
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8902 - loss: 0.3591 - val_accuracy: 0.9230 - val_loss: 0.2752
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9359 - loss: 0.2436 - val_accuracy: 0.

In [20]:
while True:
    user = input("0~9 사이의 숫자 5개 또는 Quit: ")
    if user == 'quit':
        print("종료합니다")
        break
    numbers = list(map(int, user.split(' ')))
    array_numbers = np.array([numbers])
    padded_numbers = pad_sequences(array_numbers, maxlen=5)
    prediction = model.predict (padded_numbers)
    print(np.argmax(prediction, axis=-1)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
[5 4 3 2 1]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[5 0 7 8 9]
종료합니다


# 숫자 -> 문자

In [45]:
import numpy as np 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Embedding 
from tensorflow.keras.layers import Bidirectional 
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense, Dropout, Activation
cal_len = 10
# 문자와 인덱스 매핑
chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
num_classes = len(chars)

char_to_index = {char: idx for idx, char in enumerate(chars)}
index_to_char = {idx: char for idx, char in enumerate(chars)}

# 학습 데이터 생성
train_data = np.random.choice(list(chars), size=(10000, cal_len))
label_data = np.flip(train_data, axis=1)
# 문자 데이터를 숫자 인덱스로 변환
train_data_indices = np.array([[char_to_index[char] for char in seq] for seq in train_data])
label_data_indices = np.array([[char_to_index[char] for char in seq] for seq in label_data])
print (train_data[:4])
print(label_data[ :4])
# pad_sequence 전처리
padded_train = pad_sequences (train_data_indices, maxlen=cal_len)
padded_labels = pad_sequences (label_data_indices, maxlen=cal_len)

[['Z' 'z' 'M' 'o' 'W' 'f' 'y' 'i' 'g' 'p']
 ['X' 'n' 'L' 'l' 'S' 'w' 'J' 'I' 'd' 'z']
 ['b' 'n' 'h' 'w' 'V' 'T' 'x' 'r' 'z' 'k']
 ['R' 'z' 'i' 'G' 'g' 'c' 'N' 'w' 'm' 'H']]
[['p' 'g' 'i' 'y' 'f' 'W' 'o' 'M' 'z' 'Z']
 ['z' 'd' 'I' 'J' 'w' 'S' 'l' 'L' 'n' 'X']
 ['k' 'z' 'r' 'x' 'T' 'V' 'w' 'h' 'n' 'b']
 ['H' 'm' 'w' 'N' 'c' 'g' 'G' 'i' 'z' 'R']]


In [46]:
# 모델링
model = Sequential()
model. add (Embedding(num_classes, 100, input_length=cal_len))
model.add (Bidirectional(LSTM(64, return_sequences=True)))
model. add (Dense(num_classes, activation='softmax'))
model. summary
# 모델 컴파일
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# 모델 실행
history = model. fit(padded_train, padded_labels, epochs=100, batch_size=32, validation_split=0.2)
# losser accuracy
loss, acc = model. evaluate(padded_train, padded_labels)
print(f" loss : {loss:.4f}, acc = {acc:.4f}")
# 랜덤한 영문 대소문자 5글자를 요소로 하는 20개 리스트 생성
test_data = ["".join(np.random.choice(list(chars), cal_len)) for _ in range(20)]
# 거꾸로 된 리스트 생성
expected_outputs = [s[::-1] for s in test_data]
# 모델 예측 및 정확도 계산
correct_predictions = 0
total_predictions = len(test_data)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.0620 - loss: 3.8030 - val_accuracy: 0.1836 - val_loss: 3.0548
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.2028 - loss: 2.9045 - val_accuracy: 0.2192 - val_loss: 2.6895
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.2243 - loss: 2.6027 - val_accuracy: 0.2258 - val_loss: 2.5260
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.2342 - loss: 2.4553 - val_accuracy: 0.2295 - val_loss: 2.4320
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.2364 - loss: 2.3635 - val_accuracy: 0.2320 - val_loss: 2.3755
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.2416 - loss: 2.2901 - val_accuracy: 0.2340 - val_loss: 2.3209
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.2417 - loss: 2.2353 - val_accuracy: 0.2352 - val_loss: 2.2754
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.2457 - loss: 2.1874 - val_accu

In [48]:
correct_predictions = 0
for i, test_string in enumerate(test_data):
    numbers = [char_to_index[char] for char in test_string]
    array_numbers = np.array([numbers])
    padded_numbers = pad_sequences(array_numbers, maxlen=cal_len)
    prediction = model.predict(padded_numbers)
    predicted_indices = np.argmax(prediction, axis=-1)[0]
    predicted_chars = [index_to_char[idx] for idx in predicted_indices]
    predicted_output = "".join(predicted_chars)
    is_correct = predicted_output == expected_outputs[i]
    if is_correct:
        correct_predictions += 1
    print(f"rect : {test_string}")
    print(f"예측된 출력: {predicted_output}")
    print(f"실제 출력: {expected_outputs[i]}")
    print(f"정확여부: {'맞음' if is_correct else '틀림'}\n")

accuracy = correct_predictions / total_predictions
print(f"총 정확도: {accuracy * 100:.2f}%")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
rect : DtgaQBBTdP
예측된 출력: TdTBBgattD
실제 출력: PdTBBQagtD
정확여부: 틀림

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
rect : gYQsXQabOm
예측된 출력: OObaQXsYYg
실제 출력: mObaQXsQYg
정확여부: 틀림

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
rect : ovNxZYUVCJ
예측된 출력: JCVUYZxNvo
실제 출력: JCVUYZxNvo
정확여부: 맞음

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
rect : cJLnoPHcQQ
예측된 출력: QQcHPonLJc
실제 출력: QQcHPonLJc
정확여부: 맞음

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
rect : NBvNutiTUR
예측된 출력: UUTituNNBN
실제 출력: RUTituNvBN
정확여부: 틀림

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
rect : xmGxfsAHaX
예측된 출력: XaHHsfxGmx
실제 출력: XaHAsfxGmx
정확여부: 틀림

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
rect : QQFWwnrahw
예측된 출력: wharnwWFQQ
실제 출력: wharnwWFQQ
정확여부: 맞음

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
rect : WwIlJvleLQ
예측된 출력: QLelvJlIwW
실제 출력: QLelvJlIwW
정확여부: 맞음

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
rect : iXsDDXiFda
예측된 출력: adFiXDDDXL
실제 출력: adFiXDDsXi
정확여부: 틀림

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
rect : FfQlyjDuMk
예측된 출력: kuuDjylQfF
실제 출력