In [1]:
from sklearn.model_selection import KFold
import numpy as np

n_samples = 20
X = np.arange(n_samples)

k  =10
kf = KFold(n_splits=k, shuffle=False)

for train_index, test_index in kf.split(X):
    print(train_index, "\t", test_index)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 	 [0 1]
[ 0  1  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 	 [2 3]
[ 0  1  2  3  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 	 [4 5]
[ 0  1  2  3  4  5  8  9 10 11 12 13 14 15 16 17 18 19] 	 [6 7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 18 19] 	 [8 9]
[ 0  1  2  3  4  5  6  7  8  9 12 13 14 15 16 17 18 19] 	 [10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 14 15 16 17 18 19] 	 [12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 16 17 18 19] 	 [14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 18 19] 	 [16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17] 	 [18 19]


케이폴드 교차검증

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

import pandas as pd
import numpy as np

In [7]:
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)
df =pd.read_csv('data/sonar.csv', header=None)
dataset = df.values
X = dataset[:, 0:60]

Y_obj = dataset[:, 60]
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

In [12]:
n_fold = 10
skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=seed)

In [14]:
accuracy = []

for train, test in skf.split(X, Y):
    model = Sequential()
    model.add(Dense(24, input_dim=60, activation='relu'))
    model.add(Dense(10, activation='relu')) 
    model.add(Dense(1, activation='sigmoid'))
    model. compile(loss='mean_squared_error' ,optimizer='adam' ,metrics=['accuracy'])
    ##× = dataset[:, 0:60].astype(float)를 쓰면 아래 두줄 생략 가능
    
    X_train = tf.convert_to_tensor(X[train], dtype=tf.float32)
    Y_train = tf. convert_to_tensor(Y[train], dtype=tf.float32)
    model. fit(X_train, Y_train, epochs=100, batch_size=5)
    X_test = tf.convert_to_tensor(X[test], dtype=tf.float32)
    Y_test = tf.convert_to_tensor(Y[test], dtype=tf.float32)
    k_accuracy = "%.4f" % (model.evaluate(X_test, Y_test) [1])
    accuracy.append (k_accuracy)

Epoch 1/100


/opt/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 306us/step - accuracy: 0.5424 - loss: 0.2504 
Epoch 2/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 280us/step - accuracy: 0.5280 - loss: 0.2411
Epoch 3/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 264us/step - accuracy: 0.6482 - loss: 0.2326
Epoch 4/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7160 - loss: 0.2244
Epoch 5/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 263us/step - accuracy: 0.7529 - loss: 0.2147
Epoch 6/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 279us/step - accuracy: 0.7873 - loss: 0.2050
Epoch 7/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 259us/step - accuracy: 0.7692 - loss: 0.1948
Epoch 8/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 282us/step - accuracy: 0.7635 - loss: 0.1852
Epoch 9/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 267us/step - accuracy: 0.7685 - loss: 0.1773
Epoch 10/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 273us/step - accuracy: 0.7789 - loss: 0.1701
Epoch 11/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 284us/step - accuracy: 0.7803 - loss: 0.1641
Epoch 12/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 265us/ste

In [15]:
print("\n %.f fold accuracy:" % n_fold, accuracy)


 10 fold accuracy: ['0.7143', '0.6667', '0.7619', '0.7619', '0.8571', '0.7143', '0.7143', '0.7619', '0.9000', '0.8500']


In [17]:
X.dtype

dtype('O')

In [18]:
Y.dtype

dtype('int64')